const ACTION_GET_SMTP_CONFIG = "GET_SMTP_CONFIG";
const ACTION_SAVE_SMTP_CONFIG = "SAVE_CONFIG";
const ACTION_INIT_SMTP = "INIT_SMTP";

export { ACTION_GET_SMTP_CONFIG, ACTION_SAVE_SMTP_CONFIG, ACTION_INIT_SMTP };
