const ACTION_SEND_EMAIL = "SEND_EMAIL";
const ACTION_SEND_EMAIL_ALL_USERS = "SEND_EMAIL_ALL_USERS";
const ACTION_SEND_EMAIL_ALL_API_USERS = "SEND_EMAIL_ALL_API_USERS";
const ACTION_SEND_EMAIL_WAITING_TIME_REPORTS =
  "SEND_EMAIL_WAITING_TIME_REPORTS";

export {
  ACTION_SEND_EMAIL,
  ACTION_SEND_EMAIL_ALL_API_USERS,
  ACTION_SEND_EMAIL_ALL_USERS,
  ACTION_SEND_EMAIL_WAITING_TIME_REPORTS,
};
